# Changes here will be overwritten by Copier
_commit: v0.0.38
_src_path: gh:LabAutomationAndScreening/copier-python-package-template
create_docs: false
description: Pulumi helpers
full_repo_url: https://github.com/LabAutomationAndScreening/lab-auto-pulumi
is_frozen_executable: false
is_open_source: true
package_name: lab-auto-pulumi
primary_author: Eli Fine
python_ci_versions:
- 3.12.7
- 3.13.2
python_package_registry: PyPI
python_version: 3.12.7
repo_name: lab-auto-pulumi
repo_org_name: LabAutomationAndScreening
ssh_port_number: 64123
use_codecov: true
use_windows_in_ci: false
use_windows_in_exe_ci: false

